version: "2"

services:
  datastore:
    image: postgres:11.4
    volumes:
      - "./build/datastore:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore
    networks:
      - aleph_default

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./build/redis-data:/data
    networks:
      - aleph_default

  shell:
    build: .
    command: /bin/bash
    links:
      - redis
      - datastore
    volumes:
      - "./build/data:/data"
      - "./config:/crawlers/config"
      - "./src:/crawlers/src"
    tmpfs:
      - "/tmp"
    networks:
      - aleph_default

networks:
  aleph_default:
    external: true