version: "2"

services:
  datastore:
    image: postgres:11.4
    volumes:
      - "./build/datastore:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./build/redis-data:/data

  worker:
    build: .
    command: memorious process
    links:
      - redis
      - datastore
    volumes:
      - "./build/data:/data"
      - "./config:/crawlers/config"
      - "./src:/crawlers/src"
    tmpfs:
      - "/tmp"

  ui:
    build: .
    command: gunicorn -t 900 -w 4 -b 0.0.0.0:8000 --log-level info --log-file - memorious.ui.views:app
    links:
      - redis
      - datastore
    volumes:
      - "./build/data:/data"
      - "./config:/crawlers/config"
      - "./src:/crawlers/src"
    tmpfs:
      - "/tmp"
    ports:
      - "8000:8000"